# Generated by Django 2.0.2 on 2018-03-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_title', models.CharField(max_length=100, verbose_name='fanfic title')),
                ('fic_text', models.TextField(verbose_name='fanfic text')),
                ('fic_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='FicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=150, verbose_name='link text')),
                ('link_url', models.CharField(max_length=255, verbose_name='link URL')),
                ('fanfic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fic.Fanfic')),
            ],
        ),
    ]
