# Generated by Django 2.0.2 on 2018-03-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficlink',
            old_name='fanfic_id',
            new_name='fanfic',
        ),
    ]
