# Generated by Django 2.0.2 on 2018-03-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fic', '0003_auto_20180307_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='fanfic title')),
                ('text', models.TextField(verbose_name='fanfic text')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='link text')),
                ('url', models.CharField(max_length=255, verbose_name='link URL')),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fic.Fanfic')),
            ],
        ),
    ]
